const fs = require('fs');
const path = require('path');

const layoutPath = path.join(__dirname, 'src', 'app', 'layout.tsx');
const backupPath = path.join(__dirname, 'src', 'app', 'layout.backup.tsx');

// Create backup if it doesn't exist
if (!fs.existsSync(backupPath)) {
  fs.copyFileSync(layoutPath, backupPath);
  console.log('Backup layout created');
}

// Watch for changes to layout file
fs.watchFile(layoutPath, (curr, prev) => {
  console.log('Layout file changed, checking...');
  
  fs.readFile(layoutPath, 'utf8', (err, data) => {
    if (err) {
      console.log('Error reading layout file:', err);
      return;
    }
    
    // Check if it's the basic Next.js layout
    if (data.includes('Generated by Next.js') || data.includes('title: \'Next.js\'')) {
      console.log('❌ Layout was overwritten by Next.js, restoring...');
      
      // Copy backup to main layout
      fs.copyFile(backupPath, layoutPath, (err) => {
        if (err) {
          console.log('Error restoring layout:', err);
        } else {
          console.log('✅ Layout restored successfully!');
        }
      });
    } else {
      console.log('✅ Layout is correct');
    }
  });
});

console.log('🔍 Watching layout file for changes...');

